### ISSUE TITLE
`--use_ring_loss` uses both Entropic Open-Set and Objectosphere Loss?

### ISSUE THREAD

**Issue by Embeddave** [Vastlab/Reducing-Network-Agnostophobia#5]
Hi @akshay-raj-dhamija thank you for this work and for sharing the code.

Could you please clarify the definition of the Objectosphere loss?

My understanding from the paper is that it's a separate loss function, only applied to the hidden layer before the final output layer, i.e., what the code calls `ring_loss`.
https://github.com/Vastlab/Reducing-Network-Agnostophobia/blob/581b3f06aeedb737e83a8610573f02299e2416b2/MNIST/Mnist_Training.py#L66
```
"""
Objectosphere loss function.
"""
def ring_loss(y_true,y_pred):
    pred=K.sqrt(K.sum(K.square(y_pred),axis=1))
    error=K.mean(K.square(
        # Loss for Knowns having magnitude greater than knownsMinimumMag
        y_true[:,0]*(K.maximum(knownsMinimumMag-pred,0.))
        # Add two losses
        +
        # Loss for unKnowns having magnitude greater than unknownsMaximumMag
        y_true[:,1]*pred
    ))
    return error
```

But it seems that when you set the `--use_ring_loss` flag, you still end up applying Entropic Open Set loss as well, because the `Y_train` target for the unknown classes is a vector of probabilities `0.1` (that is, the inverse 1/C over the C known classes).
https://github.com/Vastlab/Reducing-Network-Agnostophobia/blob/581b3f06aeedb737e83a8610573f02299e2416b2/MNIST/Mnist_Training.py#L179

```python
elif args.use_ring_loss:
    
    X_train,Y_train,sample_weights,Y_pred_with_flags=model_tools.concatenate_training_data(mnist,letters.X_train,0.1,ring_loss=True)
    knownsMinimumMag = Input((1,), dtype='float32', name='knownsMinimumMag')
    knownsMinimumMag_ = np.ones((X_train.shape[0]))*args.Minimum_Knowns_Magnitude
```

which gives me
```python
>>> Y_train
array([[0. , 0. , 0. , ..., 0. , 0. , 1. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ],
       ...,
       [0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1]])
```

Am I right the code behaves this way, and if so is this intended behavior? If it is, should I understand that the Objectosphere loss includes both a term for the ring loss, as well as a term for the  entropic open-Set loss?

Thanks for clarifying

**Comment by akshay-raj-dhamija** [comment]
Hello thanks for the detailed question.
You are right. Objectosphere loss (J<sub>R</sub>) is the equation (2) of the [paper](https://arxiv.org/pdf/1811.04110.pdf), which shows that it is combined with the entropic openset loss (J<sub>E</sub>). So yes objectosphere loss contains entropic openset loss, this is because just learning the feature magnitudes won't be much use if we do not learn classification as well, since that is the end goal.
In hindsight the `ring_loss` should had been named something like the `magnitude_loss` to signify it as being the second term of the equation and the `--use_ring_loss` argument should had been called `--objectosphere_loss`. Anyways I did notice you have been making some useful modifications on your fork. If you are able to fix these ambiguities discussed above please feel free to submit a pull request and I would be happy to merge your changes.
If you need any further clarifications, please let me know.

**Comment by Embeddave** [comment]
Got it, thank you @akshay-raj-dhamija !

You are totally right, I had failed to see the J<sub>E</sub> term.

That's helpful, will close for now.

May follow up about a PR after surviving a couple of deadlines 😫
